#pragma once
#define TABLERO_HORIZONTAL_FACIL 3
#define TABLERO_VERTICAL_FACIL 3
#define TABLERO_VERTICAL_NORMAL 4
#define TABLERO_HORIZONTAL_NORMAL 4 //definir tamaño tableros
#define TABLERO_VERTICAL_DIFICIL 5
#define TABLERO_HORIZONTAL_DIFICIL 5